### PR TITLE
Fixed compiler error in files ICel.cs and ReanimatorState.cs

### PR DESCRIPTION
**Pull request by Terranbyte**
In the above mentioned files all public modifiers were removed from the interfaces inside, the reason being they caused the compiler error CS0106.

### CODE REVIEW

**Comment by aarthificial** [comment]
Thanks for the fix!
The workflow failed due to some licensing issues described in #13 
I'll try to take care of that asap
